### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by desconection** [Ryzzzen/manaflux#1]
C:\Users\Matheus\AppData\Local\Programs\manaflux\resources\app.asar\node_modules\request-promise-core\lib\errors.js:14 Uncaught (in promise) RequestErrorcause: Error: connect ECONNREFUSED 127.0.0.1:50363
    at Object._errnoException (util.js:1024:11)
    at _exceptionWithHostPort (util.js:1046:20)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1182:14)error: Error: connect ECONNREFUSED 127.0.0.1:50363
    at Object._errnoException (util.js:1024:11)
    at _exceptionWithHostPort (util.js:1046:20)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1182:14)message: "Error: connect ECONNREFUSED 127.0.0.1:50363"name: "RequestError"options: {uri: "https://riot:NOwyaKdelLAOIER2mYix6Q@127.0.0.1:50363/lol-game-data/assets/v1/summoner-spells.json", transform: undefined, simple: true, resolveWithFullResponse: false, callback: ƒ, …}response: undefinedstack: "RequestError: Error: connect ECONNREFUSED 127.0.0.1:50363↵    at new RequestError (C:\Users\Matheus\AppData\Local\Programs\manaflux\resources\app.asar\node_modules\request-promise-core\lib\errors.js:14:15)↵    at Request.plumbing.callback (C:\Users\Matheus\AppData\Local\Programs\manaflux\resources\app.asar\node_modules\request-promise-core\lib\plumbing.js:87:29)↵    at Request.RP$callback [as _callback] (C:\Users\Matheus\AppData\Local\Programs\manaflux\resources\app.asar\node_modules\request-promise-core\lib\plumbing.js:46:31)↵    at self.callback (C:\Users\Matheus\AppData\Local\Programs\manaflux\resources\app.asar\node_modules\request\request.js:185:22)↵    at emitOne (events.js:116:13)↵    at Request.emit (events.js:211:7)↵    at Request.onRequestError (C:\Users\Matheus\AppData\Local\Programs\manaflux\resources\app.asar\node_modules\request\request.js:877:8)↵    at emitOne (events.js:116:13)↵    at ClientRequest.emit (events.js:211:7)↵    at TLSSocket.socketErrorListener (_http_client.js:387:9)"__proto__: Error

**Comment by desconection** [comment]
stays like this forever http://prntscr.com/kjer3b

**Comment by thomas-cardon** [comment]
I'm still pushing updates and fixing things, sorry. Have you tried restarting it ? In that case, can you try pressing `Ctrl+Shift+I`, then click to the Console tab, then type in `Mana.store.clear();`, then restart the program. This error usually means that it couldn't connect to something, in that case to your client.

**Comment by desconection** [comment]
i tried restarting and typing Mana.store.clear(); on console , its stay the same...

**Comment by thomas-cardon** [comment]
On what region do you play? EUW, NA... ?

**Comment by desconection** [comment]
Brazil

**Comment by desconection** [comment]
The new version still's dont work

**Comment by thomas-cardon** [comment]
It might be the reason why it's not working. Is it still the same error?

**Comment by desconection** [comment]
yes, the same error

**Comment by desconection** [comment]
```
RequestErrorcause: Error: connect ECONNREFUSED 127.0.0.1:50363
    at Object._errnoException (util.js:1024:11)
    at _exceptionWithHostPort (util.js:1046:20)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1182:14)error: Error: connect ECONNREFUSED 127.0.0.1:50363
    at Object._errnoException (util.js:1024:11)
    at _exceptionWithHostPort (util.js:1046:20)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1182:14)message: "Error: connect ECONNREFUSED 127.0.0.1:50363"name: "RequestError"options: {uri: "https://riot:NOwyaKdelLAOIER2mYix6Q@127.0.0.1:50363/lol-game-data/assets/v1/champion-summary.json", transform: undefined, simple: true, resolveWithFullResponse: false, callback: ƒ, …}response: undefinedstack: "RequestError: Error: connect ECONNREFUSED 127.0.0.1:50363↵    at new RequestError (C:\Users\Matheus\AppData\Local\Programs\manaflux\resources\app.asar\node_modules\request-promise-core\lib\errors.js:14:15)↵    at Request.plumbing.callback (C:\Users\Matheus\AppData\Local\Programs\manaflux\resources\app.asar\node_modules\request-promise-core\lib\plumbing.js:87:29)↵    at Request.RP$callback [as _callback] (C:\Users\Matheus\AppData\Local\Programs\manaflux\resources\app.asar\node_modules\request-promise-core\lib\plumbing.js:46:31)↵    at self.callback (C:\Users\Matheus\AppData\Local\Programs\manaflux\resources\app.asar\node_modules\request\request.js:185:22)↵    at emitOne (events.js:116:13)↵    at Request.emit (events.js:211:7)↵    at Request.onRequestError (C:\Users\Matheus\AppData\Local\Programs\manaflux\resources\app.asar\node_modules\request\request.js:877:8)↵    at emitOne (events.js:116:13)↵    at ClientRequest.emit (events.js:211:7)↵    at TLSSocket.socketErrorListener (_http_client.js:387:9)"__proto__: Error
```

**Comment by thomas-cardon** [comment]
To explain a bit, my program tries to read some data from your client first, such as the champions, summoner spells, etc. I'll try making an account on the BR servers and I'll try to see if that's the reason why it's not working. If it is, I'll make another patch.

**Comment by thomas-cardon** [comment]
On my side, the program works, even in BR region. You're sure you don't have any errors before?

**Comment by desconection** [comment]
The only error is this http://prntscr.com/kjsih7

**Comment by desconection** [comment]
````
Uncaught (in promise) 
RequestError
cause
:
Error: connect ECONNREFUSED 127.0.0.1:50363 at Object._errnoException (util.js:1024:11) at _exceptionWithHostPort (util.js:1046:20) at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1182:14)
error
:
Error: connect ECONNREFUSED 127.0.0.1:50363 at Object._errnoException (util.js:1024:11) at _exceptionWithHostPort (util.js:1046:20) at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1182:14)
message
:
"Error: connect ECONNREFUSED 127.0.0.1:50363"
name
:
"RequestError"
options
:
{uri: "https://riot:NOwyaKdelLAOIER2mYix6Q@127.0.0.1:50363/lol-game-data/assets/v1/champion-summary.json", transform: undefined, simple: true, resolveWithFullResponse: false, callback: ƒ, …}
response
:
undefined
stack
:
"RequestError: Error: connect ECONNREFUSED 127.0.0.1:50363↵    at new RequestError (C:\Users\Matheus\AppData\Local\Programs\manaflux\resources\app.asar\node_modules\request-promise-core\lib\errors.js:14:15)↵    at Request.plumbing.callback (C:\Users\Matheus\AppData\Local\Programs\manaflux\resources\app.asar\node_modules\request-promise-core\lib\plumbing.js:87:29)↵    at Request.RP$callback [as _callback] (C:\Users\Matheus\AppData\Local\Programs\manaflux\resources\app.asar\node_modules\request-promise-core\lib\plumbing.js:46:31)↵    at self.callback (C:\Users\Matheus\AppData\Local\Programs\manaflux\resources\app.asar\node_modules\request\request.js:185:22)↵    at emitOne (events.js:116:13)↵    at Request.emit (events.js:211:7)↵    at Request.onRequestError (C:\Users\Matheus\AppData\Local\Programs\manaflux\resources\app.asar\node_modules\request\request.js:877:8)↵    at emitOne (events.js:116:13)↵    at ClientRequest.emit (events.js:211:7)↵    at TLSSocket.socketErrorListener (_http_client.js:387:9)"
__proto__
:
Error

**Comment by thomas-cardon** [comment]
Do you have an anti-virus on, or a proxy, a VPN or anything?

**Comment by desconection** [comment]
nothing, no proxy, no anti virus, no vpn

**Comment by thomas-cardon** [comment]
Do you start ManaFlux, before, after League? Have you tried restarting it in administrator mode ? Go into the console tab again and type this: `Mana.store.get('leaguePath')`, then tell me what it says. For now I didn't found the issue but I keep looking.

**Comment by thomas-cardon** [comment]
Issue closed, since there's no response, and your issue might be fixed. In case it is not, feel free to open it again.
